kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-ca
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtICCQC+fvRDLrP9vjANBgkqhkiG9w0BAQsFADA3MQswCQYDVQQGEwJD
    SDETMBEGA1UECgwKYmRtc2t5Lm5ldDETMBEGA1UEAwwKYmRtc2t5Lm5ldDAeFw0y
    MDEwMTcxMjI4NTlaFw0yMzA4MDcxMjI4NTlaMDcxCzAJBgNVBAYTAkNIMRMwEQYD
    VQQKDApiZG1za3kubmV0MRMwEQYDVQQDDApiZG1za3kubmV0MIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEA0SgRg1gOkEr7valgpfd9gjPhC0hxWQ5CwpnM
    Qv+6VrSSDZgAg874dGqUeAQ5BQECZ0I6OQ4214XY2VyWZNrWBNGBkllmgcBqf80Z
    mKXW2jN2oWlnDXETIsm5TrSEGevwbPgaXd3O/aPm275dV9r4cNW22HO7Zaa06NI3
    x9Pwlf2yMzCVmprRe4RxQUbzlgo2aQS4BQRk/RuHKEBLGtBNyNezmMNsv91oqCL6
    dwVjyESlOVYLh3Q6tu+XrB5OmwwS3oiPoyI1ZtB1usbngjAVcjRKTIIw9DRYADSA
    FfUz2FCB62u74oEG0T1Vm/SA3We/bQdi7Jgolc6kqF72zyGWt0nHDxDuhvyPf290
    UyJHJ91vXwxUzv19xaBY/yh9mNf2QuQaKpT67Hcm2l6zaN47rJrPp1q/p9RoOz3b
    2UX4xDxU+XhQRpBJMYPn7mjoKZryFGmzueKi2JUI8V3VeaNNOUdEw17EpZoib+2r
    7/gZtLifm+xVqZnb2fqDx32y3U4SioU8C0RwiO2b1ulWV9cD1Mzk7F9zKP0rxwta
    xcdeySRTfdly2OwXphtH7QhPHtKuW5Vt9ZZilAnXau13wYT/LA5xu6mReGfMDDHK
    sC1GDQ1sVfTNiI/BDe7V89c9a6H0wL3Q/L4UMJBYlIZHIqjpC80N2NXJrsjmdQqY
    srWTo3ECAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAS1LvR9ink4WeBXDtocbb2Lcw
    2w3bp91x6oqDPkRegiSjk/ij8M5iLODb7bhfSdphMuJNRizCAxuhQ9GlZVr0Th8V
    sy0dG2N5FJyoKrtV7La8pVfCzt6mwcgZnQ44l2VT3IYDFLYQhXdk5lEr8j8e4/o0
    hZNOhg9OuqxJq2tCM/bekPtSS+eS8mpr2WjqIa6qzQLJp53mNIMP9YUIZOJQNaxV
    nrccGr3tFrmzs6gY6F4IOrnliINz3/rnIHYmsAWGeFE43kinMI7wo5xcqWTpb+nk
    ffrlIMYuEyv6PqbG57MqaZB8JlGkpk5jJv7EJ3FNRF2cQn4bqPe2JXGR9LoGJFuN
    Cty1R0ShXAljSYhSrHa+14qH0MmEGBn/a04gyjTSquIBF4QcYAuRiW2YNSRg3fmp
    /6LiVVClR7nrKg/gu02XpxMvWurgDBIsdQFWniIudO94AcWSf6krV1nsmTusjSAa
    IW6cwAEA0xNSpJe5fcW5+Na12Kwn16J7Eai8OYn8pq7vAWtESaQcR2OvAY4MGNHE
    1cOLTfgfWh9TKpyE3hr9/AokY5qGFY3IQ1t0SDUqDQbdnXN8CuDDoGQLj6x/fIXU
    eyy+nuMJkYJj/t4orig74MYo8kUEexLy0yulr51XfDOWsO+AjnosgkfWLrgGIr4A
    EakRQSgWkP0VsJ0QIfw=
    -----END CERTIFICATE-----